services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sara
      POSTGRES_PASSWORD: sara123
      POSTGRES_DB: sara_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: