STATE_IDLE = "idle"
STATE_ADDING_TASK = "adding_task"
STATE_PLANNING = "planning"
STATE_REVIEWING_TASKS = "reviewing_tasks"
STATE_REVIEWING_PENDING_TASKS = "reviewing_pending_tasks"
STATE_REVIEW_CONFIRMING = "review_confirming"
STATE_CONFIRMING_BULK_COMPLETE = "confirming_bulk_complete"
STATE_CONFIRMING_BACKLOG_REVIEW = "confirming_backlog_review"
STATE_CONFIRMING_RESCHEDULE_BACKLOG = "confirming_reschedule_backlog"
STATE_CONFIRMING_DELETE = "confirming_delete"

VALID_SESSION_STATES = (
    STATE_IDLE,
    STATE_ADDING_TASK,
    STATE_PLANNING,
    STATE_REVIEWING_TASKS,
    STATE_REVIEWING_PENDING_TASKS,
    STATE_REVIEW_CONFIRMING,
    STATE_CONFIRMING_BULK_COMPLETE,
    STATE_CONFIRMING_BACKLOG_REVIEW,
    STATE_CONFIRMING_RESCHEDULE_BACKLOG,
    STATE_CONFIRMING_DELETE,
)

SESSION_STATES_WITH_TTL = tuple(
    state
    for state in VALID_SESSION_STATES
    if state != STATE_IDLE
)

PERIOD_TODAY = "today"
PERIOD_YESTERDAY = "yesterday"
PERIOD_THIS_WEEK = "this_week"
PERIOD_LAST_WEEK = "last_week"
PERIOD_OVERDUE = "overdue"

VALID_RANGE_PERIODS = (
    PERIOD_TODAY,
    PERIOD_YESTERDAY,
    PERIOD_THIS_WEEK,
    PERIOD_LAST_WEEK,
)

VALID_BULK_COMPLETE_PERIODS = VALID_RANGE_PERIODS + (PERIOD_OVERDUE,)
